name: AngularCI

on:
  push:
    branches:
    - master
    - develop
    - 'release/**'
    tags:        
    - v*
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - master
    - develop
    - 'release/**'
    tags:        
    - v*

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10,11,12]
    steps:
    - uses: actions/checkout@v1
    - name: Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: npm install and npm run build
      run: |
        npm run build
  Build:
    needs: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10,11,12]
    steps:
    - uses: actions/checkout@v1
    - name: Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: npm install and npm run build
      run: |
        npm ci
        npm run build:ci
